import type {
  Hotel,
  Guest,
  Stay,
  Message,
  ServiceRequest,
  Review,
  Recommendation,
  User,
  DashboardStats,
  Conversation,
  Analytics,
} from '../types';

// =============================================
// MOCK HOTELS
// =============================================

export const mockHotels: Hotel[] = [
  {
    id: 'hotel-001',
    name: 'Hôtel Le Marais',
    slug: 'hotel-le-marais',
    primaryColor: '#c9a84c',
    secondaryColor: '#0f172a',
    accentColor: '#e8c97a',
    theme: 'boutique',
    address: '12 Rue de Bretagne',
    city: 'Paris',
    country: 'France',
    phone: '+33 1 42 72 60 00',
    email: 'contact@hotel-le-marais.fr',
    website: 'https://hotel-le-marais.fr',
    stars: 4,
    description: 'Boutique hôtel de charme au cœur du Marais historique de Paris.',
    languages: ['fr', 'en', 'de', 'es'],
    defaultLanguage: 'fr',
    status: 'active',
    plan: 'pro',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-06-20T14:30:00Z',
    guestAppUrl: '/guest/hotel-le-marais',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=https://app.concierge-os.com/hotel-le-marais',
    settings: {
      id: 'settings-001',
      hotelId: 'hotel-001',
      wifiName: 'LeMarais_Guests',
      wifiPassword: 'Paris2024!',
      checkInTime: '15:00',
      checkOutTime: '12:00',
      breakfastStart: '07:00',
      breakfastEnd: '10:30',
      breakfastIncluded: true,
      roomServiceAvailable: true,
      roomServiceHours: '07:00 - 23:00',
      receptionPhone: '+33 1 42 72 60 00',
      emergencyPhone: '+33 6 12 34 56 78',
      welcomeMessage: 'Bienvenue à l\'Hôtel Le Marais ! Nous sommes ravis de vous accueillir.',
      goodbyeMessage: 'Merci pour votre séjour. À très bientôt !',
      autoReplyEnabled: true,
      autoReplyMessage: 'Merci pour votre message. Notre équipe vous répond dans les plus brefs délais.',
      satisfactionAlertThreshold: 3,
      marketingOptinDefault: false,
    },
  },
  {
    id: 'hotel-002',
    name: 'Villa Côte d\'Azur',
    slug: 'villa-cote-dazur',
    primaryColor: '#0ea5e9',
    secondaryColor: '#0f172a',
    accentColor: '#38bdf8',
    theme: 'modern',
    address: '45 Promenade des Anglais',
    city: 'Nice',
    country: 'France',
    phone: '+33 4 93 80 12 34',
    email: 'welcome@villa-cotedazur.fr',
    stars: 5,
    description: 'Hôtel de luxe avec vue panoramique sur la Méditerranée.',
    languages: ['fr', 'en', 'it', 'ru'],
    defaultLanguage: 'fr',
    status: 'active',
    plan: 'enterprise',
    createdAt: '2024-02-10T09:00:00Z',
    updatedAt: '2024-06-18T11:00:00Z',
    guestAppUrl: '/guest/villa-cote-dazur',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=https://app.concierge-os.com/villa-cote-dazur',
  },
  {
    id: 'hotel-003',
    name: 'Château Bordeaux',
    slug: 'chateau-bordeaux',
    primaryColor: '#7c3aed',
    secondaryColor: '#1e1b4b',
    accentColor: '#a78bfa',
    theme: 'classic',
    address: '8 Cours du Chapeau Rouge',
    city: 'Bordeaux',
    country: 'France',
    phone: '+33 5 56 81 22 00',
    email: 'info@chateau-bordeaux.fr',
    stars: 4,
    description: 'Demeure historique au cœur du vignoble bordelais.',
    languages: ['fr', 'en'],
    defaultLanguage: 'fr',
    status: 'draft',
    plan: 'starter',
    createdAt: '2024-05-20T08:00:00Z',
    updatedAt: '2024-06-01T16:00:00Z',
  },
];

// =============================================
// MOCK USERS
// =============================================

export const mockUsers: User[] = [
  {
    id: 'user-001',
    email: 'admin@concierge-os.com',
    firstName: 'Alexandre',
    lastName: 'Dupont',
    role: 'super_admin',
    isActive: true,
    lastLoginAt: new Date().toISOString(),
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-002',
    hotelId: 'hotel-001',
    email: 'manager@hotel-le-marais.fr',
    firstName: 'Sophie',
    lastName: 'Martin',
    role: 'hotel_admin',
    isActive: true,
    lastLoginAt: new Date(Date.now() - 3600000).toISOString(),
    createdAt: '2024-01-16T09:00:00Z',
  },
  {
    id: 'user-003',
    hotelId: 'hotel-001',
    email: 'reception@hotel-le-marais.fr',
    firstName: 'Thomas',
    lastName: 'Bernard',
    role: 'receptionist',
    isActive: true,
    lastLoginAt: new Date(Date.now() - 7200000).toISOString(),
    createdAt: '2024-02-01T09:00:00Z',
  },
];

// =============================================
// MOCK GUESTS
// =============================================

export const mockGuests: Guest[] = [
  {
    id: 'guest-001',
    hotelId: 'hotel-001',
    firstName: 'James',
    lastName: 'Williams',
    email: 'james.williams@email.com',
    phone: '+44 7911 123456',
    nationality: 'British',
    language: 'en',
    marketingConsent: true,
    gdprConsent: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'guest-002',
    hotelId: 'hotel-001',
    firstName: 'Marie',
    lastName: 'Dubois',
    email: 'marie.dubois@email.com',
    phone: '+33 6 12 34 56 78',
    nationality: 'French',
    language: 'fr',
    marketingConsent: false,
    gdprConsent: true,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'guest-003',
    hotelId: 'hotel-001',
    firstName: 'Klaus',
    lastName: 'Schmidt',
    email: 'k.schmidt@email.de',
    phone: '+49 170 1234567',
    nationality: 'German',
    language: 'de',
    marketingConsent: true,
    gdprConsent: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'guest-004',
    hotelId: 'hotel-001',
    firstName: 'Isabelle',
    lastName: 'Fontaine',
    email: 'i.fontaine@email.fr',
    phone: '+33 7 98 76 54 32',
    nationality: 'French',
    language: 'fr',
    marketingConsent: true,
    gdprConsent: true,
    createdAt: new Date(Date.now() - 86400000 * 0.5).toISOString(),
  },
];

// =============================================
// MOCK STAYS
// =============================================

export const mockStays: Stay[] = [
  {
    id: 'stay-001',
    hotelId: 'hotel-001',
    guestId: 'guest-001',
    roomNumber: '204',
    checkInDate: new Date(Date.now() - 86400000 * 2).toISOString(),
    checkOutDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    status: 'active',
    source: 'booking',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    guest: mockGuests[0],
  },
  {
    id: 'stay-002',
    hotelId: 'hotel-001',
    guestId: 'guest-002',
    roomNumber: '312',
    checkInDate: new Date(Date.now() - 86400000 * 1).toISOString(),
    checkOutDate: new Date(Date.now() + 86400000 * 3).toISOString(),
    status: 'active',
    source: 'direct',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    guest: mockGuests[1],
  },
  {
    id: 'stay-003',
    hotelId: 'hotel-001',
    guestId: 'guest-003',
    roomNumber: '118',
    checkInDate: new Date(Date.now() - 86400000 * 3).toISOString(),
    checkOutDate: new Date(Date.now() + 86400000 * 1).toISOString(),
    status: 'active',
    source: 'expedia',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    guest: mockGuests[2],
  },
  {
    id: 'stay-004',
    hotelId: 'hotel-001',
    guestId: 'guest-004',
    roomNumber: '401',
    checkInDate: new Date(Date.now() - 3600000 * 5).toISOString(),
    checkOutDate: new Date(Date.now() + 86400000 * 4).toISOString(),
    status: 'active',
    source: 'direct',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    guest: mockGuests[3],
  },
];

// =============================================
// MOCK MESSAGES
// =============================================

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    hotelId: 'hotel-001',
    stayId: 'stay-001',
    guestId: 'guest-001',
    sender: 'guest',
    content: 'Hello, could you please arrange a taxi to Charles de Gaulle airport for tomorrow at 6am?',
    status: 'read',
    isRead: true,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    guest: mockGuests[0],
    stay: mockStays[0],
  },
  {
    id: 'msg-002',
    hotelId: 'hotel-001',
    stayId: 'stay-001',
    guestId: 'guest-001',
    sender: 'reception',
    content: 'Bonjour Mr. Williams! Bien sûr, je vais organiser votre taxi pour 5h45 afin d\'être à l\'heure. Votre chauffeur s\'appellera Jean-Pierre. Bonne nuit!',
    status: 'delivered',
    isRead: true,
    createdAt: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    guest: mockGuests[0],
    stay: mockStays[0],
  },
  {
    id: 'msg-003',
    hotelId: 'hotel-001',
    stayId: 'stay-002',
    guestId: 'guest-002',
    sender: 'guest',
    content: 'Bonsoir, est-il possible d\'avoir des oreillers supplémentaires dans la chambre 312 ?',
    status: 'delivered',
    isRead: false,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    guest: mockGuests[1],
    stay: mockStays[1],
  },
  {
    id: 'msg-004',
    hotelId: 'hotel-001',
    stayId: 'stay-003',
    guestId: 'guest-003',
    sender: 'guest',
    content: 'Die Klimaanlage in meinem Zimmer funktioniert nicht richtig. Können Sie bitte jemanden schicken?',
    status: 'sent',
    isRead: false,
    createdAt: new Date(Date.now() - 900000).toISOString(),
    guest: mockGuests[2],
    stay: mockStays[2],
  },
  {
    id: 'msg-005',
    hotelId: 'hotel-001',
    stayId: 'stay-004',
    guestId: 'guest-004',
    sender: 'guest',
    content: 'Bonjour ! Je viens d\'arriver et ma chambre est magnifique. Pourriez-vous me recommander un bon restaurant dans le quartier ?',
    status: 'delivered',
    isRead: false,
    createdAt: new Date(Date.now() - 600000).toISOString(),
    guest: mockGuests[3],
    stay: mockStays[3],
  },
];

// =============================================
// MOCK CONVERSATIONS
// =============================================

export const mockConversations: Conversation[] = [
  {
    stayId: 'stay-004',
    guestId: 'guest-004',
    guestName: 'Isabelle Fontaine',
    roomNumber: '401',
    lastMessage: 'Bonjour ! Je viens d\'arriver et ma chambre est magnifique...',
    lastMessageAt: new Date(Date.now() - 600000).toISOString(),
    unreadCount: 1,
    isUrgent: false,
    messages: [mockMessages[4]],
    guest: mockGuests[3],
    stay: mockStays[3],
  },
  {
    stayId: 'stay-003',
    guestId: 'guest-003',
    guestName: 'Klaus Schmidt',
    roomNumber: '118',
    lastMessage: 'Die Klimaanlage in meinem Zimmer funktioniert nicht richtig...',
    lastMessageAt: new Date(Date.now() - 900000).toISOString(),
    unreadCount: 1,
    isUrgent: true,
    messages: [mockMessages[3]],
    guest: mockGuests[2],
    stay: mockStays[2],
  },
  {
    stayId: 'stay-002',
    guestId: 'guest-002',
    guestName: 'Marie Dubois',
    roomNumber: '312',
    lastMessage: 'Bonsoir, est-il possible d\'avoir des oreillers supplémentaires...',
    lastMessageAt: new Date(Date.now() - 1800000).toISOString(),
    unreadCount: 1,
    isUrgent: false,
    messages: [mockMessages[2]],
    guest: mockGuests[1],
    stay: mockStays[1],
  },
  {
    stayId: 'stay-001',
    guestId: 'guest-001',
    guestName: 'James Williams',
    roomNumber: '204',
    lastMessage: 'Bonne nuit!',
    lastMessageAt: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    unreadCount: 0,
    isUrgent: false,
    messages: [mockMessages[0], mockMessages[1]],
    guest: mockGuests[0],
    stay: mockStays[0],
  },
];

// =============================================
// MOCK SERVICE REQUESTS
// =============================================

export const mockServiceRequests: ServiceRequest[] = [
  {
    id: 'req-001',
    hotelId: 'hotel-001',
    stayId: 'stay-003',
    guestId: 'guest-003',
    category: 'maintenance',
    title: 'Climatisation défaillante',
    description: 'La climatisation ne fonctionne pas correctement dans la chambre 118.',
    status: 'urgent',
    priority: 'urgent',
    createdAt: new Date(Date.now() - 900000).toISOString(),
    updatedAt: new Date(Date.now() - 900000).toISOString(),
    guest: mockGuests[2],
    stay: mockStays[2],
  },
  {
    id: 'req-002',
    hotelId: 'hotel-001',
    stayId: 'stay-002',
    guestId: 'guest-002',
    category: 'towels',
    title: 'Oreillers supplémentaires',
    description: 'La cliente souhaite des oreillers supplémentaires pour la chambre 312.',
    status: 'new',
    priority: 'medium',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
    guest: mockGuests[1],
    stay: mockStays[1],
  },
  {
    id: 'req-003',
    hotelId: 'hotel-001',
    stayId: 'stay-001',
    guestId: 'guest-001',
    category: 'taxi',
    title: 'Taxi CDG - 6h00',
    description: 'Taxi demandé pour l\'aéroport CDG demain à 6h00 du matin.',
    status: 'in_progress',
    priority: 'high',
    assignedTo: 'Thomas Bernard',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    guest: mockGuests[0],
    stay: mockStays[0],
  },
  {
    id: 'req-004',
    hotelId: 'hotel-001',
    stayId: 'stay-004',
    guestId: 'guest-004',
    category: 'restaurant',
    title: 'Recommandation restaurant',
    description: 'La cliente souhaite une recommandation de restaurant dans le quartier.',
    status: 'new',
    priority: 'low',
    createdAt: new Date(Date.now() - 600000).toISOString(),
    updatedAt: new Date(Date.now() - 600000).toISOString(),
    guest: mockGuests[3],
    stay: mockStays[3],
  },
];

// =============================================
// MOCK REVIEWS
// =============================================

export const mockReviews: Review[] = [
  {
    id: 'review-001',
    hotelId: 'hotel-001',
    stayId: 'stay-001',
    guestId: 'guest-001',
    overallRating: 5,
    cleanlinessRating: 5,
    serviceRating: 5,
    locationRating: 5,
    valueRating: 4,
    comment: 'Absolutely wonderful stay! The staff were incredibly helpful and the room was immaculate.',
    hasProblem: false,
    isPublic: true,
    alertSent: false,
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    guest: mockGuests[0],
    stay: mockStays[0],
  },
  {
    id: 'review-002',
    hotelId: 'hotel-001',
    stayId: 'stay-003',
    guestId: 'guest-003',
    overallRating: 2,
    cleanlinessRating: 4,
    serviceRating: 3,
    locationRating: 5,
    valueRating: 2,
    comment: 'Die Klimaanlage funktionierte nicht und es hat lange gedauert bis jemand kam.',
    problem: 'Climatisation défaillante, délai d\'intervention trop long',
    hasProblem: true,
    isPublic: false,
    alertSent: true,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    guest: mockGuests[2],
    stay: mockStays[2],
  },
];

// =============================================
// MOCK RECOMMENDATIONS
// =============================================

export const mockRecommendations: Recommendation[] = [
  {
    id: 'rec-001',
    hotelId: 'hotel-001',
    category: 'restaurant',
    name: 'Chez Janou',
    description: 'Bistrot provençal authentique avec une carte de pastis impressionnante.',
    address: '2 Rue Roger Verlomme, 75003 Paris',
    distance: '150m',
    walkingTime: '2 min',
    rating: 4.5,
    priceRange: '€€',
    phone: '+33 1 42 72 28 41',
    openingHours: 'Lun-Sam 12h-15h, 19h-23h30',
    tags: ['Provençal', 'Bistrot', 'Vin naturel'],
    isHighlighted: true,
    sortOrder: 1,
  },
  {
    id: 'rec-002',
    hotelId: 'hotel-001',
    category: 'cafe',
    name: 'Café de Flore',
    description: 'Institution parisienne légendaire, idéal pour le petit déjeuner.',
    address: '172 Bd Saint-Germain, 75006 Paris',
    distance: '1.2km',
    walkingTime: '15 min',
    rating: 4.2,
    priceRange: '€€€',
    openingHours: 'Tous les jours 7h30-01h30',
    tags: ['Historique', 'Terrasse', 'Brunch'],
    isHighlighted: true,
    sortOrder: 2,
  },
  {
    id: 'rec-003',
    hotelId: 'hotel-001',
    category: 'museum',
    name: 'Centre Pompidou',
    description: 'Musée national d\'art moderne, architecture emblématique.',
    address: 'Place Georges-Pompidou, 75004 Paris',
    distance: '400m',
    walkingTime: '5 min',
    rating: 4.6,
    priceRange: '€€',
    phone: '+33 1 44 78 12 33',
    website: 'https://www.centrepompidou.fr',
    openingHours: 'Mer-Lun 11h-21h',
    tags: ['Art moderne', 'Architecture', 'Incontournable'],
    isHighlighted: true,
    sortOrder: 3,
  },
  {
    id: 'rec-004',
    hotelId: 'hotel-001',
    category: 'bakery',
    name: 'Du Pain et des Idées',
    description: 'La meilleure boulangerie du Marais, pain au chocolat exceptionnel.',
    address: '34 Rue Yves Toudic, 75010 Paris',
    distance: '600m',
    walkingTime: '8 min',
    rating: 4.8,
    priceRange: '€',
    openingHours: 'Lun-Ven 7h-20h',
    tags: ['Artisanal', 'Viennoiseries', 'Incontournable'],
    isHighlighted: false,
    sortOrder: 4,
  },
  {
    id: 'rec-005',
    hotelId: 'hotel-001',
    category: 'transport',
    name: 'Métro Saint-Sébastien – Froissart',
    description: 'Station de métro ligne 8, accès rapide à toute la ville.',
    address: '86 Bd Beaumarchais, 75011 Paris',
    distance: '200m',
    walkingTime: '3 min',
    tags: ['Métro', 'Ligne 8', 'Transport'],
    isHighlighted: false,
    sortOrder: 5,
  },
];

// =============================================
// MOCK ANALYTICS
// =============================================

export const mockAnalytics: Analytics = {
  hotelId: 'hotel-001',
  period: '30days',
  qrScans: 342,
  activeGuests: 18,
  avgSatisfaction: 4.3,
  totalMessages: 156,
  totalRequests: 89,
  resolvedRequests: 76,
  avgResponseTime: 12,
  positiveReviews: 28,
  negativeReviews: 3,
  popularServices: [
    { category: 'Taxi', count: 34 },
    { category: 'Restaurant', count: 28 },
    { category: 'Room Service', count: 21 },
    { category: 'Serviettes', count: 18 },
    { category: 'Maintenance', count: 12 },
  ],
  satisfactionTrend: [
    { date: '01/06', rating: 4.1 },
    { date: '05/06', rating: 4.3 },
    { date: '10/06', rating: 4.2 },
    { date: '15/06', rating: 4.5 },
    { date: '20/06', rating: 4.3 },
    { date: '25/06', rating: 4.4 },
    { date: '30/06', rating: 4.6 },
  ],
  messageVolume: [
    { date: '01/06', count: 18 },
    { date: '05/06', count: 24 },
    { date: '10/06', count: 31 },
    { date: '15/06', count: 22 },
    { date: '20/06', count: 28 },
    { date: '25/06', count: 35 },
    { date: '30/06', count: 19 },
  ],
};

export const mockDashboardStats: DashboardStats = {
  activeGuests: 18,
  newMessages: 3,
  pendingRequests: 4,
  urgentAlerts: 1,
  avgSatisfaction: 4.3,
  qrScansToday: 12,
  requestsResolved: 76,
  satisfactionTrend: 'up',
};
